all:
  vars:
    ansible_ssh_private_key_file: ~/.ssh/my_private_key.rsa
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
  children:
    noprod:
      hosts:
        host1:
        host2:
    prod:
      hosts:
        host3:
        host4:
        
